export const agenda_teste = [
  {
    id: 44,
    start_time: "2026-06-05T10:00:00",
    doctor: "Dr. Igor Carvalho",
    specialtie: "Endocrinologia",
    clinic: "Medicina Integrada",
  },
  {
    id: 54,
    start_time: "2026-06-06T11:00:00",
    doctor: "Dr. Samuel Antunes",
    specialtie: "Endocrinologia",
    clinic: "Hospital das Nações",
  },
  {
    id: 40,
    start_time: "2026-06-04T16:00:00",
    doctor: "Dr. Eduardo Costa",
    specialtie: "Ginecologia",
    clinic: "Clínica Bem Estar",
  },
  {
    id: 50,
    start_time: "2026-06-05T17:00:00",
    doctor: "Dr. Otavio Castro",
    specialtie: "Ginecologia",
    clinic: "Centro Pediátrico",
  },
  {
    id: 43,
    start_time: "2026-06-05T09:00:00",
    doctor: "Dra. Helena Souza",
    specialtie: "Neurologia",
    clinic: "Centro de Diagnóstico Alpha",
  },
  {
    id: 53,
    start_time: "2026-06-06T10:00:00",
    doctor: "Dra. Roberta Viana",
    specialtie: "Neurologia",
    clinic: "Centro de Reabilitação",
  },
  {
    id: 42,
    start_time: "2026-06-05T08:00:00",
    doctor: "Dr. Gabriel Almeida",
    specialtie: "Oftalmologia",
    clinic: "Clínica Ortopédica Sul",
  },
  {
    id: 52,
    start_time: "2026-06-06T09:00:00",
    doctor: "Dr. Quiterio Jorge",
    specialtie: "Oftalmologia",
    clinic: "Clínica Dermatológica Lótus",
  },
  {
    id: 39,
    start_time: "2026-06-04T15:00:00",
    doctor: "Dra. Daniela Lima",
    specialtie: "Ortopedia",
    clinic: "Pronto Socorro Central",
  },
  {
    id: 49,
    start_time: "2026-06-05T16:00:00",
    doctor: "Dra. Nicole Farias",
    specialtie: "Ortopedia",
    clinic: "Clínica da Mulher",
  },
  {
    id: 38,
    start_time: "2026-06-04T14:00:00",
    doctor: "Dr. Caio Oliveira",
    specialtie: "Pediatria",
    clinic: "Hospital Santa Helena",
  },
  {
    id: 48,
    start_time: "2026-06-05T15:00:00",
    doctor: "Dr. Mauricio Nunes",
    specialtie: "Pediatria",
    clinic: "Espaço Saúde",
  },
  {
    id: 41,
    start_time: "2026-06-04T17:00:00",
    doctor: "Dra. Fernanda Rocha",
    specialtie: "Psiquiatria",
    clinic: "Instituto da Visão",
  },
  {
    id: 51,
    start_time: "2026-06-06T08:00:00",
    doctor: "Dra. Patricia Melo",
    specialtie: "Psiquiatria",
    clinic: "Instituto de Neurologia",
  },
  {
    id: 45,
    start_time: "2026-06-05T11:00:00",
    doctor: "Dra. Julia Pereira",
    specialtie: "Urologia",
    clinic: "Hospital do Coração",
  },
  {
    id: 55,
    start_time: "2026-06-06T13:00:00",
    doctor: "Dra. Tatiana Gomes",
    specialtie: "Urologia",
    clinic: "Clínica São José",
  },
];
